### ISSUE TITLE
doxyconfig repository should have LICENSE file

### ISSUE THREAD

**Issue by cathyjf** [LizardByte/doxyconfig#18]
There is a strong argument that nothing in the doxyconfig repository is subject to copyright in the United States because the configuration is neither original nor creative, and both of those elements are required for a work to be subject to be copyright.

That said, to avoid any potential uncertainties, I recommend that the doxyconfig repository should have a LICENSE file explicitly disclaiming any copyright, perhaps by using CC-0. Alternatively, if you want to leave open the possibility that original and/or creative works might be added to the doxyconfig repository, you could assert that the code is license under the GPLv3, like Sunshine.

Also, I should add that I haven't reviewed the doxyconfig repository that closely, so if there's anything in or that is original and creative already, disregard what I said about that.

In any case, it's not ideal that this repository has no LICENSE information, particularly since this code is already incorporated into LizardByte/Sunshine.

**Comment by ReenigneArcher** [comment]
Mostly this is just a configuration along with some basic CMake and bash. Probably the only thing somewhat original is the custom readthedocs javascript search: https://github.com/LizardByte/doxyconfig/blob/master/doxyconfig-readthedocs-search.js

Unless there's a strong objection, I think I'll go with AGPLv3 since the docs are generally hosted online.
